spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.videmeamentkjybkyoeq
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=5
server.port=8080

Secret code: To change   IMPORTANT 
notus.qr.hmacSecret=${QR_HMAC_SECRET:R8kT%fZc1!aP@9Jx0#sM5qE^W2B7L&y}
notus.qr.ttlSeconds=60
gemini.api.key=twoj kod gemini
gemini.model=gemini-2.5-flash
